import {useEffect,useMemo,useRef,useState} from 'react';
import {Page} from '../../components/Page';
import {inspectCadFile,type CadInspection} from '../../core/cad/modelInspector';
import {cadStorageUsage,deleteCadBinary,getCadBinary,saveCadBinary} from '../../core/cad/blobStore';
import {canClaimOfficialCad,validateDimensions,type DimensionalValidation,type Dimensions3D} from '../../core/cad/dimensionalValidation';

type CadKind='machine'|'punch'|'die'|'assembly';
type Verification='official'|'validated'|'parametric'|'pending';
interface CadAsset {id:string;name:string;kind:CadKind;manufacturer:string;model:string;source:string;license:string;verification:Verification;fileName:string;fileSize:number;inspection:CadInspection;createdAt:string;binaryStored:boolean;expectedDimensions?:Dimensions3D;dimensionalValidation?:DimensionalValidation;}
const KEY='plegar-pro-cad-assets-v014';
const LEGACY_KEY='plegar-pro-cad-assets-v013';
const labels:Record<CadKind,string>={machine:'Máquina',punch:'Punzón',die:'Matriz',assembly:'Montaje'};
function GeometryPreview({inspection}:{inspection:CadInspection}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current,points=inspection.previewPoints;if(!canvas||!points?.length)return;const ctx=canvas.getContext('2d');if(!ctx)return;const w=canvas.width=640,h=canvas.height=330;ctx.clearRect(0,0,w,h);ctx.fillStyle='#07111d';ctx.fillRect(0,0,w,h);const b=inspection.bounds;if(!b)return;const sx=w*.72/Math.max(b.size[0],.001),sy=h*.72/Math.max(b.size[2]||b.size[1],.001),scale=Math.min(sx,sy);ctx.strokeStyle='rgba(65,210,255,.38)';ctx.fillStyle='#62d9ff';ctx.lineWidth=1;for(const p of points){const x=w/2+(p[0]-(b.min[0]+b.max[0])/2)*scale;const z=h/2-(p[2]-(b.min[2]+b.max[2])/2)*scale-(p[1]-(b.min[1]+b.max[1])/2)*scale*.22;ctx.fillRect(x,z,1.4,1.4);}ctx.strokeStyle='#16d9a8';ctx.strokeRect(w*.1,h*.1,w*.8,h*.8);},[inspection]);return <canvas className="cad-preview-canvas" ref={ref} aria-label="Vista previa geométrica CAD"/>}
export function CadAssetsPage(){
  const [assets,setAssets]=useState<CadAsset[]>(()=>{try{const current=localStorage.getItem(KEY);const legacy=localStorage.getItem(LEGACY_KEY);return JSON.parse(current??legacy??'[]').map((a:CadAsset)=>({...a,binaryStored:Boolean(a.binaryStored)}))}catch{return []}});
  const [file,setFile]=useState<File|null>(null);const [inspection,setInspection]=useState<CadInspection|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const [usage,setUsage]=useState({files:0,bytes:0});
  const [kind,setKind]=useState<CadKind>('machine');const [manufacturer,setManufacturer]=useState('');const [model,setModel]=useState('');const [source,setSource]=useState('');const [license,setLicense]=useState('');const [verification,setVerification]=useState<Verification>('pending');const [query,setQuery]=useState('');
  const [expectedX,setExpectedX]=useState('');const [expectedY,setExpectedY]=useState('');const [expectedZ,setExpectedZ]=useState('');const [tolerance,setTolerance]=useState('0.5');
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify(assets)),[assets]);useEffect(()=>{cadStorageUsage().then(setUsage).catch(()=>setUsage({files:0,bytes:0}))},[assets]);
  const filtered=useMemo(()=>assets.filter(a=>`${a.name} ${a.manufacturer} ${a.model} ${a.fileName}`.toLowerCase().includes(query.toLowerCase())),[assets,query]);
  const dimensionalValidation=useMemo(()=>{if(!inspection?.bounds||![expectedX,expectedY,expectedZ].every(v=>Number(v)>0))return undefined;return validateDimensions({x:inspection.bounds.size[0],y:inspection.bounds.size[1],z:inspection.bounds.size[2]},{x:Number(expectedX),y:Number(expectedY),z:Number(expectedZ)},Math.max(.001,Number(tolerance)||.5));},[inspection,expectedX,expectedY,expectedZ,tolerance]);
  async function choose(next:File|null){setFile(next);setInspection(null);setMessage('');if(!next)return;setBusy(true);try{setInspection(await inspectCadFile(next));}catch(error){setMessage(error instanceof Error?error.message:'No se pudo inspeccionar el archivo.')}finally{setBusy(false)}}
  async function save(){if(!file||!inspection||!manufacturer.trim()||!model.trim())return;const officialAllowed=canClaimOfficialCad({source,license,sha256:inspection.sha256,validation:dimensionalValidation});if(verification==='official'&&!officialAllowed){setMessage('No se puede registrar como CAD oficial: faltan fuente/licencia, huella o validación dimensional dentro de tolerancia.');return;}const id=crypto.randomUUID();let binaryStored=false;try{await saveCadBinary({id,fileName:file.name,mimeType:file.type||'application/octet-stream',size:file.size,sha256:inspection.sha256,blob:file});binaryStored=true;}catch(error){setMessage(`Metadatos guardados, pero el archivo binario no pudo almacenarse: ${error instanceof Error?error.message:'error desconocido'}`)}const expectedDimensions=dimensionalValidation?{x:Number(expectedX),y:Number(expectedY),z:Number(expectedZ)}:undefined;const item:CadAsset={id,name:`${manufacturer} ${model}`,kind,manufacturer:manufacturer.trim(),model:model.trim(),source:source.trim(),license:license.trim(),verification,fileName:file.name,fileSize:file.size,inspection,createdAt:new Date().toISOString(),binaryStored,expectedDimensions,dimensionalValidation};setAssets(v=>[item,...v]);setFile(null);setInspection(null);setModel('');setExpectedX('');setExpectedY('');setExpectedZ('');if(binaryStored)setMessage('Modelo, archivo y validación CAD almacenados localmente.');}
  async function download(asset:CadAsset){const stored=await getCadBinary(asset.id);if(!stored){setMessage('El archivo binario no está disponible en este navegador.');return;}const url=URL.createObjectURL(stored.blob);const link=document.createElement('a');link.href=url;link.download=stored.fileName;link.click();URL.revokeObjectURL(url);}
  async function remove(asset:CadAsset){await deleteCadBinary(asset.id).catch(()=>undefined);setAssets(v=>v.filter(x=>x.id!==asset.id));}
  return <Page title="Registro CAD" subtitle="Inspección, almacenamiento local y trazabilidad de máquinas, punzones, matrices y montajes">
    <section className="panel cad-storage-summary"><b>Almacenamiento CAD local</b><span>{usage.files} archivos · {(usage.bytes/1024/1024).toFixed(2)} MB</span><small>Los binarios se guardan en IndexedDB del navegador y no se envían a ningún servidor.</small></section>
    {message&&<section className="panel notice"><p>{message}</p></section>}
    <section className="panel cad-import-grid"><div className="cad-form"><label>Archivo CAD<input type="file" accept=".obj,.stl,.step,.stp,.iges,.igs,.gltf,.glb,.dxf" onChange={e=>choose(e.target.files?.[0]??null)}/></label><label>Tipo<select value={kind} onChange={e=>setKind(e.target.value as CadKind)}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Fabricante<input value={manufacturer} onChange={e=>setManufacturer(e.target.value)} placeholder="TRUMPF, AMADA, Bystronic…"/></label><label>Modelo / referencia<input value={model} onChange={e=>setModel(e.target.value)} placeholder="TrumaBend V85, V16, P88…"/></label><label>Fuente oficial<input value={source} onChange={e=>setSource(e.target.value)} placeholder="Portal, catálogo o identificador"/></label><label>Licencia / autorización<input value={license} onChange={e=>setLicense(e.target.value)} placeholder="Condición de uso o permiso"/></label><label>Estado<select value={verification} onChange={e=>setVerification(e.target.value as Verification)}><option value="official">CAD oficial</option><option value="validated">Validado dimensionalmente</option><option value="parametric">Reconstrucción paramétrica</option><option value="pending">Pendiente</option></select></label><fieldset className="dimension-validation"><legend>Validación dimensional (mm)</legend><label>X oficial<input type="number" min="0" step="0.001" value={expectedX} onChange={e=>setExpectedX(e.target.value)}/></label><label>Y oficial<input type="number" min="0" step="0.001" value={expectedY} onChange={e=>setExpectedY(e.target.value)}/></label><label>Z oficial<input type="number" min="0" step="0.001" value={expectedZ} onChange={e=>setExpectedZ(e.target.value)}/></label><label>Tolerancia<input type="number" min="0.001" step="0.001" value={tolerance} onChange={e=>setTolerance(e.target.value)}/></label>{dimensionalValidation&&<div className={dimensionalValidation.valid?"validation-ok":"validation-error"}><b>{dimensionalValidation.valid?"Dimensiones validadas":"Dimensiones fuera de tolerancia"}</b><small>{dimensionalValidation.summary}</small>{dimensionalValidation.checks.map(c=><small key={c.axis}>{c.axis.toUpperCase()}: {c.measured.toFixed(3)} / {c.expected.toFixed(3)} mm · Δ {c.difference.toFixed(3)}</small>)}</div>}</fieldset><button type="button" onClick={save} disabled={!file||!inspection||!manufacturer.trim()||!model.trim()}>Registrar modelo y archivo</button></div>
    <div className="cad-inspection">{busy?<p>Inspeccionando archivo…</p>:inspection?<><h3>Resultado de inspección</h3>{inspection.previewPoints?.length?<GeometryPreview inspection={inspection}/>:null}<dl><div><dt>Formato</dt><dd>{inspection.format}</dd></div><div><dt>Vértices</dt><dd>{inspection.vertexCount}</dd></div><div><dt>Triángulos</dt><dd>{inspection.triangleCount}</dd></div><div><dt>Dimensiones</dt><dd>{inspection.bounds?inspection.bounds.size.map(v=>v.toFixed(2)).join(' × '):'Traductor requerido'}</dd></div><div><dt>SHA-256</dt><dd className="hash">{inspection.sha256??'No disponible'}</dd></div></dl>{inspection.warnings.map(w=><small key={w}>{w}</small>)}</>:<p>Selecciona un OBJ o STL para inspeccionar su geometría y previsualizarlo. STEP, IGES, GLB y DXF se registran con trazabilidad, pero requieren traductor específico para medirlos.</p>}</div></section>
    <section className="panel library-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en el registro CAD"/><span>{filtered.length} modelos</span></section>
    <section className="panel cad-assets-list">{filtered.length===0?<p>No hay modelos CAD registrados.</p>:filtered.map(a=><article key={a.id}><header><div><b>{a.name}</b><small>{labels[a.kind]} · {a.fileName}</small></div><span className={`cad-status ${a.verification}`}>{a.verification}</span></header><dl><div><dt>Formato</dt><dd>{a.inspection.format}</dd></div><div><dt>Geometría</dt><dd>{a.inspection.triangleCount} triángulos</dd></div><div><dt>Archivo</dt><dd>{a.binaryStored?'Conservado localmente':'Solo metadatos'}</dd></div><div><dt>Fuente</dt><dd>{a.source||'Sin indicar'}</dd></div><div><dt>Validación</dt><dd>{a.dimensionalValidation?a.dimensionalValidation.summary:'Sin validación dimensional'}</dd></div><div><dt>Registrado</dt><dd>{new Date(a.createdAt).toLocaleString()}</dd></div></dl><div className="inline-actions"><button type="button" onClick={()=>download(a)} disabled={!a.binaryStored}>Descargar CAD</button><button type="button" onClick={()=>remove(a)}>Eliminar registro</button></div></article>)}</section>
    <section className="panel notice"><b>Importante</b><p>Registrar un archivo no lo convierte automáticamente en CAD oficial. Para ese estado deben conservarse la fuente, la licencia y la verificación dimensional. Los binarios se almacenan solo en este navegador; para compartirlos entre dispositivos será necesario un servidor documental.</p></section>
  </Page>;
}
