import {useMemo,useState} from 'react';
import {Page} from '../../components/Page';
import {createEmptyCatalogPackage,downloadCatalogPackage,validateCatalogPackage,type TechnicalCatalogPackage} from '../../core/cad/catalogPackage';
import {machines,tools} from '../../data/catalog';
import {compareCatalogPackages,createSyncState,type CatalogDiff,type CatalogSyncState} from '../../core/cad/catalogSync';

const builtInCatalog:TechnicalCatalogPackage={schema:'plegar-pro.catalog.v1',packageId:'plegar-pro-built-in-v1',title:'Catálogo paramétrico inicial Plegar Pro',publisher:'Plegar Pro',generatedAt:new Date().toISOString(),items:[
  ...machines.map(m=>({id:`machine-${m.id}`,kind:'machine' as const,manufacturer:m.manufacturer,reference:m.id,name:m.name,source:m.source,verification:m.verified?'validated' as const:'parametric' as const,dimensions:{lengthMm:m.lengthMm,strokeMm:m.strokeMm,daylightMm:m.daylightMm},metadata:{forceT:m.forceT,throatMm:m.throatMm,clamp:m.clamp}})),
  ...tools.map(t=>({id:`tool-${t.id}`,kind:t.kind,manufacturer:t.manufacturer,reference:t.id,name:t.name,source:t.source,verification:t.verified?'validated' as const:'parametric' as const,dimensions:{height:t.height,width:t.width,radius:t.radius,angle:t.angle,...(t.v?{v:t.v}:{})},metadata:{family:t.family,clamp:t.clamp,loadKnM:t.loadKnM??0}}))
]};

const KEY='plegar-pro-technical-catalog-packages-v015';const LEGACY_KEY='plegar-pro-technical-catalog-packages-v014';const SYNC_KEY='plegar-pro-catalog-sync-v015';
export function CatalogManagerPage(){
  const [packages,setPackages]=useState<TechnicalCatalogPackage[]>(()=>{try{const stored=JSON.parse(localStorage.getItem(KEY)??localStorage.getItem(LEGACY_KEY)??'[]') as TechnicalCatalogPackage[];return stored.length?stored:[builtInCatalog]}catch{return [builtInCatalog]}});
  const [sync,setSync]=useState<Record<string,CatalogSyncState>>(()=>{try{return JSON.parse(localStorage.getItem(SYNC_KEY)??'{}')}catch{return {}}});
  const [selected,setSelected]=useState<TechnicalCatalogPackage|null>(builtInCatalog);
  const [kindFilter,setKindFilter]=useState('all');const [catalogQuery,setCatalogQuery]=useState('');const [result,setResult]=useState<ReturnType<typeof validateCatalogPackage>|null>(null);const [diff,setDiff]=useState<CatalogDiff|null>(null);const [message,setMessage]=useState('');
  const total=useMemo(()=>packages.reduce((sum,p)=>sum+p.items.length,0),[packages]);
  const visibleItems=useMemo(()=>selected?.items.filter(item=>(kindFilter==='all'||item.kind===kindFilter)&&`${item.manufacturer} ${item.reference} ${item.name}`.toLowerCase().includes(catalogQuery.toLowerCase()))??[],[selected,kindFilter,catalogQuery]);
  function persist(next:TechnicalCatalogPackage[],nextSync=sync){setPackages(next);setSync(nextSync);localStorage.setItem(KEY,JSON.stringify(next));localStorage.setItem(SYNC_KEY,JSON.stringify(nextSync));}
  async function importFile(file:File|null){if(!file)return;setMessage('');try{const data=JSON.parse(await file.text());const validation=validateCatalogPackage(data);setResult(validation);if(validation.valid){const pkg=data as TechnicalCatalogPackage;const previous=packages.find(p=>p.packageId===pkg.packageId);setDiff(previous?compareCatalogPackages(previous,pkg):{added:pkg.items.map(i=>i.id),removed:[],changed:[],unchanged:0});const next=[pkg,...packages.filter(p=>p.packageId!==pkg.packageId)];const nextSync={...sync,[pkg.packageId]:createSyncState(pkg)};persist(next,nextSync);setSelected(pkg);setMessage(previous?'Catálogo actualizado y diferencias calculadas.':'Catálogo importado y trazabilidad inicial creada.');}}catch{setResult({valid:false,errors:['El archivo no contiene JSON válido.'],warnings:[],itemCount:0});}}
  function createTemplate(){downloadCatalogPackage(createEmptyCatalogPackage('Plantilla de catálogo Plegar Pro'));}
  function remove(id:string){const next=packages.filter(p=>p.packageId!==id);const nextSync={...sync};delete nextSync[id];persist(next,nextSync);if(selected?.packageId===id)setSelected(null);}
  async function checkSource(pkg:TechnicalCatalogPackage){if(!pkg.sourceUrl){setMessage('Este catálogo no incluye sourceUrl.');return;}const started=new Date().toISOString();try{const response=await fetch(pkg.sourceUrl,{method:'HEAD',mode:'cors',cache:'no-store'});const etag=response.headers.get('etag')??response.headers.get('last-modified')??undefined;const previous=sync[pkg.packageId];const status=previous?.etag&&etag&&previous.etag!==etag?'update-available':'current';const state:CatalogSyncState={packageId:pkg.packageId,sourceUrl:pkg.sourceUrl,lastImported:previous?.lastImported,lastChecked:started,etag,status,message:response.ok?(status==='update-available'?'La fuente ha cambiado; descarga e importa el nuevo paquete autorizado.':'Fuente accesible sin cambios detectados.'):`La fuente respondió ${response.status}.`};const next:Record<string,CatalogSyncState>={...sync,[pkg.packageId]:state};persist(packages,next);setMessage(state.message);}catch(error){const state:CatalogSyncState={packageId:pkg.packageId,sourceUrl:pkg.sourceUrl,lastImported:sync[pkg.packageId]?.lastImported,lastChecked:started,status:'error',message:`No se pudo comprobar automáticamente (CORS, autenticación o red): ${error instanceof Error?error.message:'error desconocido'}`};const next:Record<string,CatalogSyncState>={...sync,[pkg.packageId]:state};persist(packages,next);setMessage(state.message);}}
  return <Page title="Gestor de catálogos técnicos" subtitle="Importación, diferencias, trazabilidad y comprobación de fuentes autorizadas">
    <section className="stats"><article className="stat"><span>Paquetes</span><b>{packages.length}</b></article><article className="stat"><span>Registros</span><b>{total}</b></article><article className="stat"><span>Esquema</span><b>v1</b></article></section>
    {message&&<section className="panel notice"><p>{message}</p></section>}
    <section className="panel catalog-import"><label>Importar paquete .json<input type="file" accept=".json,.ppcatalog.json" onChange={e=>importFile(e.target.files?.[0]??null)}/></label><button type="button" onClick={createTemplate}>Descargar plantilla</button>{result&&<div className={result.valid?'catalog-valid':'catalog-invalid'}><b>{result.valid?'Paquete válido':'Paquete rechazado'}</b><span>{result.itemCount} registros</span>{result.errors.map(e=><small key={e}>{e}</small>)}{result.warnings.map(w=><small key={w}>Aviso: {w}</small>)}</div>}{diff&&<div className="catalog-diff"><b>Cambios importados</b><span>+{diff.added.length} nuevos · {diff.changed.length} modificados · -{diff.removed.length} retirados · {diff.unchanged} iguales</span></div>}</section>
    <section className="catalog-layout"><div className="panel catalog-list">{packages.length===0?<p>No hay paquetes importados.</p>:packages.map(pkg=>{const state=sync[pkg.packageId];return <article key={pkg.packageId} className={selected?.packageId===pkg.packageId?'selected':''}><button type="button" onClick={()=>setSelected(pkg)}><b>{pkg.title}</b><small>{pkg.publisher} · {pkg.items.length} registros</small><small>{state?.status??'idle'} · {state?.lastChecked?new Date(state.lastChecked).toLocaleString():'sin comprobar'}</small></button><button type="button" onClick={()=>checkSource(pkg)} disabled={!pkg.sourceUrl}>Comprobar fuente</button><button type="button" onClick={()=>downloadCatalogPackage(pkg)}>Exportar</button><button type="button" onClick={()=>remove(pkg.packageId)}>Eliminar</button></article>})}</div><div className="panel catalog-detail">{selected?<><h3>{selected.title}</h3><div className="catalog-filters"><input placeholder="Buscar fabricante, referencia o nombre" value={catalogQuery} onChange={e=>setCatalogQuery(e.target.value)}/><select value={kindFilter} onChange={e=>setKindFilter(e.target.value)}><option value="all">Todos los tipos</option><option value="machine">Máquinas</option><option value="punch">Punzones</option><option value="die">Matrices</option></select></div><p>{selected.publisher} · {new Date(selected.generatedAt).toLocaleString()}</p><p><b>Fuente:</b> {selected.sourceUrl||'No indicada'}</p><table><thead><tr><th>Tipo</th><th>Fabricante</th><th>Referencia</th><th>Estado</th></tr></thead><tbody>{visibleItems.map(item=><tr key={item.id}><td>{item.kind}</td><td>{item.manufacturer}</td><td>{item.reference}</td><td>{item.verification}</td></tr>)}</tbody></table></>:<p>Selecciona un paquete para revisar sus registros.</p>}</div></section>
    <section className="panel notice"><b>Conectores oficiales</b><p>La comprobación usa la URL declarada por el paquete. Algunos portales bloquean HEAD/CORS o requieren sesión; en ese caso Plegar Pro registra el error y exige una descarga autenticada o importación manual autorizada, sin fingir una sincronización exitosa.</p></section>
  </Page>;
}
