import {useEffect,useState} from 'react';
import {Page} from '../../components/Page';
import {useActiveProject,useAppStore} from '../../store/useAppStore';
import {machines,tools} from '../../data/catalog';

function CollisionViewport({project,punch,die,angle,collision}:{project:any;punch:any;die:any;angle:number;collision:boolean}){
 const cx=380,top=105,bendRad=(180-angle)*Math.PI/360,arm=150,lx=cx-Math.cos(bendRad)*arm,ly=top+Math.sin(bendRad)*arm,rx=cx+Math.cos(bendRad)*arm,ry=top+Math.sin(bendRad)*arm;
 return <div className={`collision-cad-viewport ${collision?'collision-hit':''}`}><svg viewBox="0 0 760 430" role="img" aria-label="Vista CAD de punzón matriz y chapa">
  <rect width="760" height="430" fill="#08131c"/>{Array.from({length:9},(_,i)=><line key={i} x1="0" y1={45+i*42} x2="760" y2={45+i*42} stroke="#6ea0b5" opacity=".18" strokeDasharray="3 8"/>)}
  <path d={`M ${cx-170} ${top-8} L ${cx+170} ${top-8} L ${cx+38} ${top+42} L ${cx} ${top+95} L ${cx-38} ${top+42} Z`} fill="#6e7e89" stroke="#d2e0e6" strokeWidth="3"/>
  <path d={`M ${cx-245} 335 L ${cx-80} 335 L ${cx} 263 L ${cx+80} 335 L ${cx+245} 335`} fill="none" stroke="#778b96" strokeWidth="26" strokeLinejoin="round"/>
  <path d={`M ${lx} ${ly} L ${cx} ${top+6} L ${rx} ${ry}`} fill="none" stroke="#dbe8ee" strokeWidth={project.thickness+5} strokeLinecap="round"/><path d={`M ${lx} ${ly} L ${cx} ${top+6} L ${rx} ${ry}`} fill="none" stroke="#8fb1c0" strokeWidth="2"/>
  <text x="22" y="30" fill="#9fdcff" fontSize="16" fontWeight="700">VISTA CAD · COLISIÓN EN TIEMPO REAL</text><text x="22" y="52" fill="#809eac" fontSize="12">Espesor {project.thickness} mm · Ángulo {Math.round(angle)}° · V{die.v??'—'}</text>
  <text x={cx} y="82" textAnchor="middle" fill="#d9e7ed" fontSize="13" fontWeight="700">PUNZÓN · {punch.name}</text><text x={cx} y="402" textAnchor="middle" fill="#d9e7ed" fontSize="13" fontWeight="700">MATRIZ · {die.name}</text>
  {collision&&<><circle cx={cx} cy={top+8} r="27" fill="#ff4258" opacity=".18"/><circle cx={cx} cy={top+8} r="17" fill="none" stroke="#ff5d70" strokeWidth="3"/><text x={cx+25} y={top-2} fill="#ff7381" fontSize="14" fontWeight="800">COLISIÓN</text></>}
 </svg></div>
}

export function CollisionsPage(){
 const project=useActiveProject();const state=useAppStore();const machine=machines.find(x=>x.id===state.selectedMachineId)??machines[0];const punch=tools.find(x=>x.id===state.selectedPunchId&&x.kind==='punch')??tools.find(x=>x.kind==='punch')!;const die=tools.find(x=>x.id===state.selectedDieId&&x.kind==='die')??tools.find(x=>x.kind==='die')!;
 const [step,setStep]=useState(0),[playing,setPlaying]=useState(false);useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setStep(v=>{if(v>=project.bends.length-1){setPlaying(false);return v}return v+1}),700);return()=>window.clearInterval(id)},[playing,project.bends.length]);
 const bend=project.bends[step]??project.bends[0];const findings:string[]=[];if(bend){const stack=punch.height+die.height+project.thickness;if(stack>machine.daylightMm)findings.push('Altura de montaje incompatible');if((die.v??0)<project.thickness*6)findings.push('V insuficiente');if(bend.angle<35&&punch.angle>=bend.angle)findings.push('Holgura angular insuficiente')}const collision=findings.length>0;
 return <Page title="Colisiones y secuencia" subtitle="Vista CAD/CAM de punzón, matriz y chapa · análisis plegado a plegado"><div className="collision-pro-page"><div className="collision-toolbar"><div><strong>ANÁLISIS DE COLISIÓN</strong><span>Paso {step+1} de {Math.max(1,project.bends.length)}</span></div><button onClick={()=>setPlaying(v=>!v)}>{playing?'Pausar':'Reproducir secuencia'}</button><button onClick={()=>setStep(0)}>Reiniciar</button></div><div className="collision-layout"><section className="panel collision-visual-panel"><CollisionViewport project={project} punch={punch} die={die} angle={bend?.angle??90} collision={collision}/><div className="collision-legend"><span>Punzón</span><span>Matriz</span><span>Chapa</span><b className={collision?'danger':'safe'}>{collision?'⚠ COLISIÓN DETECTADA':'✓ SIN COLISIÓN'}</b></div></section><aside className="panel collision-step-panel"><h3>PASOS DE PLEGADO</h3>{project.bends.length?project.bends.map((b,i)=><button key={b.id} className={i===step?'active':''} onClick={()=>{setPlaying(false);setStep(i)}}><b>P{b.order}</b><span>{b.angle}° · R{b.radius} · X{b.backgaugeX}</span><small>{i===step?'En análisis':'Pendiente'}</small></button>):<p>Añade un plegado desde Desarrollo o Programación 2D.</p>}<div className={`collision-status-card ${collision?'danger':'safe'}`}><strong>{collision?'COLISIÓN / REVISAR':'TRAYECTORIA LIBRE'}</strong><span>{collision?findings.join(' · '):'No se detectan interferencias en este paso con las reglas activas.'}</span></div><dl><div><dt>Máquina</dt><dd>{machine.name}</dd></div><div><dt>Punzón</dt><dd>{punch.name}</dd></div><div><dt>Matriz</dt><dd>{die.name}</dd></div><div><dt>Espesor</dt><dd>{project.thickness} mm</dd></div></dl></aside></div><div className="collision-kpis"><div><strong>{project.bends.length}</strong><span>pasos programados</span></div><div className={collision?'bad':'ok'}><strong>{collision?'COLISIÓN':'OK'}</strong><span>estado actual</span></div><div><strong>V{die.v??'—'}</strong><span>matriz activa</span></div><div><strong>R{bend?.radius??0}</strong><span>radio del paso</span></div></div></div></Page>
}
