import {useMemo,useState} from 'react';
import {Page} from '../../components/Page';
import {useActiveProject} from '../../store/useAppStore';

export function CurvePerfectPage(){
  const project=useActiveProject();
  const [radius,setRadius]=useState(120);const [angle,setAngle]=useState(90);const [pieceLength,setPieceLength]=useState(project.width);const [maxStep,setMaxStep]=useState(8);const [tolerance,setTolerance]=useState(.5);
  const result=useMemo(()=>{const safeRadius=Math.max(1,radius),safeAngle=Math.max(1,Math.min(180,angle));const arc=2*Math.PI*safeRadius*(safeAngle/360);const byStep=Math.max(2,Math.ceil(arc/Math.max(1,maxStep)));const byTolerance=Math.max(2,Math.ceil(Math.sqrt(safeRadius/Math.max(tolerance,.05))*safeAngle/35));const hits=Math.max(byStep,byTolerance);const spacing=arc/hits;const anglePerHit=safeAngle/hits;const chord=2*safeRadius*Math.sin(anglePerHit*Math.PI/360);const start=Math.max(0,(pieceLength-arc)/2);return{arc,hits,spacing,anglePerHit,chord,start,end:start+arc}},[radius,angle,pieceLength,maxStep,tolerance]);
  const points=Array.from({length:result.hits+1},(_,i)=>{const a=(-angle/2+i*(angle/result.hits))*Math.PI/180;return{x:250+Math.min(radius,130)*1.5*Math.sin(a),y:280-Math.min(radius,130)*1.5*Math.cos(a)}});
  return <Page title="Curva Perfecta" subtitle="Introduce radio, ángulo y longitud: Plegar Pro calcula golpes, separación y posiciones">
    <div className="engineering-grid"><section className="panel form"><label>Radio objetivo (mm)<input type="number" min="1" value={radius} onChange={e=>setRadius(Number(e.target.value))}/></label><label>Ángulo total (°)<input type="number" min="1" max="180" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></label><label>Largo de la pieza (mm)<input type="number" min="1" value={pieceLength} onChange={e=>setPieceLength(Number(e.target.value))}/></label><label>Separación máxima entre golpes (mm)<input type="number" min="1" value={maxStep} onChange={e=>setMaxStep(Number(e.target.value))}/></label><label>Tolerancia de faceteado (mm)<input type="number" min="0.05" step="0.05" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}/></label><dl><div><dt>Material</dt><dd>{project.material} · {project.thickness} mm</dd></div><div><dt>Longitud arco</dt><dd>{result.arc.toFixed(2)} mm</dd></div><div><dt>Número de golpes</dt><dd>{result.hits}</dd></div><div><dt>Separación</dt><dd>{result.spacing.toFixed(2)} mm</dd></div><div><dt>Ángulo por golpe</dt><dd>{result.anglePerHit.toFixed(3)}°</dd></div><div><dt>Zona de curva</dt><dd>{result.start.toFixed(2)} → {result.end.toFixed(2)} mm</dd></div></dl></section><section className="panel canvas-panel"><svg viewBox="0 0 500 330" className="program-svg"><polyline points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#f2b83b" strokeWidth="9" strokeLinejoin="round"/>{points.map((p,i)=><g key={i}><circle cx={p.x} cy={p.y} r="5" fill="#22d8ff"/><text x={p.x+7} y={p.y-7}>{i}</text></g>)}<text x="18" y="28">R {radius} mm · {angle}° · {pieceLength} mm · {result.hits} golpes</text></svg></section></div>
    <section className="panel"><h3>Programa de golpes</h3><div className="library-table">{Array.from({length:result.hits},(_,i)=>{const pos=result.start+i*result.spacing;return <article className="library-row" key={i}><div><b>GOLPE {i+1}</b><strong>Posición {pos.toFixed(2)} mm</strong><small>Ángulo acumulado {((i+1)*result.anglePerHit).toFixed(3)}°</small></div><dl><div><dt>Separación</dt><dd>{result.spacing.toFixed(2)}</dd></div><div><dt>Ángulo/golpe</dt><dd>{result.anglePerHit.toFixed(3)}°</dd></div><div><dt>Radio</dt><dd>{radius}</dd></div><div><dt>Cuerda</dt><dd>{result.chord.toFixed(2)}</dd></div><div><dt>Largo pieza</dt><dd>{pieceLength}</dd></div></dl></article>})}</div></section>
  </Page>
}
