import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import DxfParser from 'dxf-parser';
const app=express(),PORT=Number(process.env.PORT||8787),ROOT=path.resolve(process.cwd()),UPLOADS=path.join(ROOT,'server','uploads'),CONVERTED=path.join(ROOT,'server','converted');
await fs.mkdir(UPLOADS,{recursive:true});await fs.mkdir(CONVERTED,{recursive:true});app.use(cors());app.use(express.json());app.use('/converted',express.static(CONVERTED));
const upload=multer({dest:UPLOADS,limits:{fileSize:100*1024*1024,files:10}});
app.get('/health',(_q,res)=>res.json({ok:true,version:'19.0',converters:['DXF','SVG','STEP/IGES via FreeCAD','DWG adapter']}));
const extOf=n=>path.extname(n).toLowerCase();
async function commandExists(cmd){return new Promise(resolve=>{const p=spawn(process.platform==='win32'?'where':'which',[cmd]);p.on('close',c=>resolve(c===0));p.on('error',()=>resolve(false))})}
function infer(parsed){const lines=(parsed.entities||[]).filter(e=>e.type==='LINE'),lengths=lines.map(e=>{const a=e.vertices?.[0],b=e.vertices?.[1];return a&&b?Math.hypot((b.x||0)-(a.x||0),(b.y||0)-(a.y||0)):0}).filter(v=>v>.01).sort((a,b)=>b-a),wings=lengths.slice(0,6).map(v=>Number(v.toFixed(2))),count=Math.max(1,Math.min(5,wings.length-1));return{wings:wings.length>=2?wings:[100,50],bends:Array.from({length:count},(_,i)=>({angle:90,radius:2,direction:i%2?'Abajo':'Arriba',v:16,bendLength:800,gauge:wings[i]||50}))}}
async function dxf(file){const text=await fs.readFile(file.path,'utf8'),parsed=new DxfParser().parseSync(text),name=path.basename(file.originalname,path.extname(file.originalname))+'.json',geometry=infer(parsed);await fs.writeFile(path.join(CONVERTED,name),JSON.stringify({source:file.originalname,entities:parsed.entities?.length||0,geometry},null,2));return{status:'converted',converter:'dxf-parser',entities:parsed.entities?.length||0,output:'/converted/'+name,geometry}}
async function svg(file){const text=await fs.readFile(file.path,'utf8'),count=(text.match(/<(path|line|polyline|polygon|rect)\b/gi)||[]).length,name=path.basename(file.originalname,path.extname(file.originalname))+'.svg';await fs.copyFile(file.path,path.join(CONVERTED,name));return{status:'converted',converter:'native-svg',entities:count,output:'/converted/'+name}}
async function freecad(file){let cmd=null;for(const c of(process.platform==='win32'?['FreeCADCmd.exe','FreeCADCmd']:['FreeCADCmd','freecadcmd']))if(await commandExists(c)){cmd=c;break}if(!cmd)return{status:'adapter-ready',converter:'FreeCAD not installed',entities:0,output:null};const base=path.basename(file.originalname,path.extname(file.originalname)),outp=path.join(CONVERTED,base+'.stl'),script=path.join(CONVERTED,base+'_convert.py'),code=`import FreeCAD, Part, Mesh\ndoc=FreeCAD.newDocument("Convert")\nshape=Part.Shape()\nshape.read(r"${file.path.replaceAll('\\','\\\\')}")\nobj=doc.addObject("PartDesign::Feature","Imported")\nobj.Shape=shape\nMesh.export([obj],r"${outp.replaceAll('\\','\\\\')}")`;await fs.writeFile(script,code);return new Promise(resolve=>{const p=spawn(cmd,[script]);let err='';p.stderr.on('data',d=>err+=d);p.on('close',async c=>{await fs.rm(script,{force:true});resolve(c===0?{status:'converted',converter:'FreeCAD',entities:1,output:'/converted/'+path.basename(outp)}:{status:'failed',converter:'FreeCAD',entities:0,output:null,error:err.slice(-500)})});p.on('error',e=>resolve({status:'failed',converter:'FreeCAD',entities:0,output:null,error:e.message}))})}
async function convert(file){const e=extOf(file.originalname);if(e==='.dxf')return dxf(file);if(e==='.svg')return svg(file);if(['.step','.stp','.iges','.igs'].includes(e))return freecad(file);if(e==='.dwg')return{status:'adapter-ready',converter:'ODA/LibreDWG required',entities:0,output:null};if(['.sldprt','.sldasm','.ipt','.iam','.catpart','.x_t','.x_b'].includes(e))return{status:'adapter-ready',converter:'licensed CAD connector required',entities:0,output:null};return{status:'registered',converter:'no geometry converter',entities:0,output:null}}
app.post('/api/cad/convert',upload.array('files',10),async(req,res)=>{try{const results=[];for(const file of req.files||[]){results.push({name:file.originalname,...await convert(file)});await fs.rm(file.path,{force:true})}res.json({ok:true,results})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.listen(PORT,()=>console.log(`Plegar Pro CAD Server running on http://localhost:${PORT}`));
